#!/bin/sh
#fbpanel -p default &
#xfce4-power-manager &
#nm-applet --sm-disable &
#~/.config/startApps &
#~/.config/system_sound &
#~/.config/stop_tumblerd &
#~/.config/startConky &
#fcitx-autostart &
#/usr/bin/gnome-keyring-daemon --start --components=gpg &
#/usr/bin/gnome-keyring-daemon --start --components=ssh &
#blueman-applet &
#xmobar &
#sh -c 'xrandr --output VGA --mode 1366x768 --rate 59.79'
#sh -c 'xrandr --output eDP-1 --off'
#compton &
#nitrogen --restore &
#dunst &



