#!/bin/sh
truncate noir.patch --size 0
VERSIONPOINT="5.9.6"
cat linux/patch-$VERSIONPOINT \
       custom_config.patch \
       UKSM/uksm-5.9kai.patch \
       other/add-acs-overrides.patch \
       LL/0001-LL-kconfig-add-750Hz-timer-interrupt-kernel-config-o.patch \
       LL/0003kai2-sched-core-nr_migrate-256-increases-number-of-tasks-.patch \
       LL/0004-mm-set-8-megabytes-for-address_space-level-file-read.patch \
       zen/ZEN_INTERACTIVE_Base_config_item.patch \
       zen/ZEN_INTERACTIVE_Tune_CFS_for_interactivity.patch \
       zen/ZEN_INTERACTIVE_Add_help_text_for_the_MuQSS_tweaks.patch \
       zen/ZEN_Add_CONFIG_to_rename_the_mq-deadline_scheduler.patch \
       zen/use_kyber.patch \
       zen/ZEN_INTERACTIVE_Increase_default_writeback_thresholds.patch \
       zen/ZEN_INTERACTIVE_Tune_ondemand_governor_for_interactivity.patch \
       zen/ZEN_INTERACTIVE_Enable_background_reclaim_of_hugepages.patch \
       zen/ZEN_INTERACTIVE_Increase_max_number_of_tasks_rebalanced_at_once_kai.patch \
       zen/ZEN_Add_VHBA_driver.patch \
       zen/ZEN_Enable_additional_CPU_Optimizations_for_GCC_v10_1.patch \
       zen/ZEN_Unrestrict_CONFIG_OPTIMIZE_FOR_PERFORMANCE_O3.patch \
       zen/ZEN_Add_OpenRGB_patches.patch \
       zen/mm_Disable_watermark_boosting_by_default.patch \
       zen/vfs_keep_inodes_with_page_cache_off_the_inode_shrinker_LRU.patch \
       zen/ZEN_Add_an_option_to_make_threadirqs_the_default.patch \
       ck1/0001-MultiQueue-Skiplist-Scheduler-v0.204.patch \
       ck1/muqss_Fix_build_error_on_config_leak.patch \
       ck1/0002-Make-preemptible-kernel-default.patch \
       ck1/0003-Expose-vmsplit-for-our-poor-32-bit-users.patch \
       ck1/0004-Create-highres-timeout-variants-of-schedule_timeout-.patch \
       ck1/0005-Special-case-calls-of-schedule_timeout-1-to-use-the-.patch \
       ck1/0006-Convert-msleep-to-use-hrtimers-when-active.patch \
       ck1/0007-Replace-all-schedule-timeout-1-with-schedule_min_hrt.patch \
       ck1/0008-Replace-all-calls-to-schedule_timeout_interruptible-.patch \
       ck1/0009-Replace-all-calls-to-schedule_timeout_uninterruptibl.patch \
       ck1/0010-Don-t-use-hrtimer-overlay-when-pm_freezing-since-som.patch \
       ck1/0011-Make-hrtimer-granularity-and-minimum-hrtimeout-confi.patch \
       ck1/0014-Swap-sucks.patch \
       IBM/introduce_per-task_latency_nice_for_scheduler_hints_kai.patch \
       xanmod/0001-sched-autogroup-Add-kernel-parameter-and-config-opti.patch \
       VALVE/futex_Implement_mechanism_to_wait_on_any_of_several_futexes.patch \
       VALVE/futex_Add_Proton_compatibility_code.patch \
       other/0003-block-set-rq_affinity-2-for-full-multithreading-I-O-.patch \
       other/0005-block-bfq-Disable-low_latency-when-blk_iolatency-is-.patch \
       intel/0001-i8042-decrease-debug-message-level-to-info.patch \
       intel/0002-Increase-the-ext4-default-commit-age.patch \
       intel/0003-silence-rapl.patch \
       intel/0004-pci-pme-wakeups.patch \
       intel/0005-ksm-wakeups.patch \
       intel/0006-intel_idle-tweak-cpuidle-cstates.patch \
       intel/0007-bootstats-add-printk-s-to-measure-boot-time-in-more-.patch \
       intel/0008-smpboot-reuse-timer-calibration.patch \
       intel/0009-raid6-add-Kconfig-option-to-skip-raid6-benchmarking.patch \
       intel/0010-Initialize-ata-before-graphics.patch \
       intel/0011-give-rdrand-some-credit.patch \
       intel/0012-ipv4-tcp-allow-the-memory-tuning-for-tcp-to-go-a-lit.patch \
       intel/0013-kernel-time-reduce-ntp-wakeups.patch \
       intel/0014-init-wait-for-partition-and-retry-scan.patch \
       intel/0015-print-fsync-count-for-bootchart.patch \
       intel/0017-Enable-stateless-firmware-loading.patch \
       intel/0018-Migrate-some-systemd-defaults-to-the-kernel-defaults.patch \
       intel/0019-xattr-allow-setting-user.-attributes-on-symlinks-by-.patch \
       intel/0020-use-lfence-instead-of-rep-and-nop.patch \
       intel/0021-do-accept-in-LIFO-order-for-cache-efficiency.patch \
       intel/0022-locking-rwsem-spin-faster.patch \
       intel/0023-ata-libahci-ignore-staggered-spin-up.patch \
       intel/0024-print-CPU-that-faults.patch \
       intel/0026-nvme-workaround.patch \
       intel/0027-Don-t-report-an-error-if-PowerClamp-run-on-other-CPU.patch \
       intel/0028-Port-microcode-patches.patch \
       intel/0029-clearlinux-Add-pageflip-patches.patch \
       add_noir_version.patch \
       other/0001-ntfs3-patches.patch \
       ubuntu/futex_Handle_transient_ownerless_rtmutex_state_correctly.patch \
       ubuntu/UBUNTU_SAUCE_tools_hv_lsvmbus_add_manual_page.patch \
       ubuntu/UBUNTU_SAUCE_add_vmlinux.strip_to_BOOT_TARGETS1_on_powerpc.patch \
       ubuntu/base_packaging.patch \
       ubuntu/debian_changelog.patch \
       ubuntu/configs_based_on_Ubuntu-5.10-5.10.0-2.3_kai.patch \
       > noir.patch