#!/bin/bash

. vsrx_builder/extras/config

(echo
echo STARTING DEB INSTALLATION
echo

read FILE < $WORKPATH/configs/DEB

cp $FILE $FSPATH/tmp
cp /etc/hosts $FSPATH/etc/

mount --bind /dev $FSPATH/dev
mount --bind /var/run/dbus $FSPATH/var/lib/dbus
mount --bind /var/run/dbus $FSPATH/var/run/dbus

touch $FSPATH/tmp/script.bash
cat > $FSPATH/tmp/script.bash << "EOF"
#################### CHROOT ENVIRONMENT ####################
#!/bin/bash

export HOME=/root
export LC_ALL=C
mount none -t proc /proc
mount none -t sysfs /sys
mount none -t devpts /dev/pts
dpkg -i -G -E $FSPATH/tmp/*.deb
apt-get -f -y install
EOF
######################### on EXIT #########################
echo "apt-get clean
rm -rf /tmp/*
rm -rf /etc/hosts
umount -lf /proc
umount -lf /sys
umount -lf /dev/pts
umount -lf /var/lib/dbus
umount -lf /var/run/dbus" >> $FSPATH/tmp/script.bash

chroot $FSPATH sh /tmp/script.bash
umount -l $FSPATH/dev
zenity --info --text="Installation completed."
) | tee -a $WORKPATH/ubuntu-builder.log
