#!/bin/bash

. vsrx_builder/extras/config

cd $WORKPATH

function ubiquity_install()
{
(echo
echo STARTING UBIQUITY INSTALLATION
echo

cp /etc/hosts $FSPATH/etc/

mount --bind /dev $FSPATH/dev
mount --bind /var/run/dbus $FSPATH/var/lib/dbus
mount --bind /var/run/dbus $FSPATH/var/run/dbus

wget -O /dev/null www.google.com > /dev/null
if [ ! "$?" -eq 0 ]; then
	zenity --error --text "You are not connected to the Internet so Ubiquity cannot be installed."
fi

STYLE=$(zenity --title="Ubiquity" --list --height=230 --text="Please select your favourite Ubiquity style." --column="Select" --column="Option" TRUE Ubuntu FALSE Kubuntu FALSE Xubuntu FALSE Lubuntu --radiolist)

return_value=$?
case $return_value in
	1)
		exit
		;;
	-1)
		exit
		;;
esac

echo "# This may take a while, please be patient.."

echo $STYLE > $FSPATH/tmp/STYLE
touch $FSPATH/tmp/script.bash
cat > $FSPATH/tmp/script.bash << "EOF"
#################### CHROOT ENVIRONMENT ####################
#!/bin/bash

export HOME=/root
export LC_ALL=C
mount none -t proc /proc
mount none -t sysfs /sys
mount none -t devpts /dev/pts
apt-get update -q

read STYLE < /tmp/STYLE
case $STYLE in
	Ubuntu)
		apt-get install --yes ubiquity ubiquity-frontend-gtk ubiquity-slideshow-ubuntu
		;;
	Kubuntu)
		apt-get install --yes ubiquity ubiquity-frontend-kde ubiquity-slideshow-kubuntu
		;;
	Xubuntu)
		apt-get install --yes ubiquity ubiquity-frontend-gtk ubiquity-slideshow-xubuntu
		;;
	Lubuntu)
		apt-get install --yes ubiquity ubiquity-frontend-gtk ubiquity-slideshow-lubuntu
		;;
esac
EOF
######################### on EXIT #########################
echo "apt-get clean
rm -rf /tmp/*
rm -rf /etc/hosts
umount -lf /proc
umount -lf /sys
umount -lf /dev/pts
umount -lf /var/lib/dbus
umount -lf /var/run/dbus" >> $FSPATH/tmp/script.bash

sudo chroot $FSPATH sh /tmp/script.bash
umount -l $FSPATH/dev)|
zenity --progress --pulsate --auto-kill --auto-close

###################### Setting up ######################

# FrontEnd
if [ -d $FSPATH/usr/share/ubiquity/gtk ]; then
	echo "ubiquity-frontend-gtk" > $WORKPATH/configs/ubiquity/FRONTEND
elif [ -d $FSPATH/usr/share/ubiquity/qt ]; then
	echo "ubiquity-frontend-kde" > $WORKPATH/configs/ubiquity/FRONTEND
fi

# SlideShow
if [ -e $FSPATH/usr/share/ubiquity-slideshow/slides/icons/ubuntuone.png ]; then
	echo "ubiquity-slideshow-ubuntu" > $WORKPATH/configs/ubiquity/SLIDESHOW
elif [ -e $FSPATH/usr/share/ubiquity-slideshow/slides/icons/kubuntu-logo.png ]; then
	echo "ubiquity-slideshow-kubuntu" > $WORKPATH/configs/ubiquity/SLIDESHOW
elif [ -e $FSPATH/usr/share/ubiquity-slideshow/slides/images/gmusicbrowser_16.png ]; then
	echo "ubiquity-slideshow-xubuntu" > $WORKPATH/configs/ubiquity/SLIDESHOW
elif [ -e $FSPATH/usr/share/ubiquity-slideshow/slides/images/xpad.png ]; then
	echo "ubiquity-slideshow-lubuntu" > $WORKPATH/configs/ubiquity/SLIDESHOW
fi
}

function ubiquity_change()
{
(echo
echo STARTING UBIQUITY CHANGE
echo

cp /etc/hosts $FSPATH/etc/

mount --bind /dev $FSPATH/dev
mount --bind /var/run/dbus $FSPATH/var/lib/dbus
mount --bind /var/run/dbus $FSPATH/var/run/dbus

wget -O /dev/null www.google.com > /dev/null
if [ "$?" -ne 0 ]; then
	zenity --error --text "You are not connected to the Internet so Ubiquity cannot be changed."
fi

STYLE=$(zenity --title="Ubiquity" --list --height=230 --text="Please select your favourite Ubiquity style." --column="Select" --column="Option" TRUE Ubuntu FALSE Kubuntu FALSE Xubuntu FALSE Lubuntu --radiolist)

return_value=$?
case $return_value in
	1)
		exit
		;;
	-1)
		exit
		;;
esac

echo "# This may take a while, please be patient.."

echo $STYLE > $FSPATH/tmp/STYLE
touch $FSPATH/tmp/script.bash
cat > $FSPATH/tmp/script.bash << "EOF"
#################### CHROOT ENVIRONMENT ####################
#!/bin/bash

export HOME=/root
export LC_ALL=C
mount none -t proc /proc
mount none -t sysfs /sys
mount none -t devpts /dev/pts
apt-get update -q

apt-get purge -y ubiquity*

read STYLE < /tmp/STYLE
case $STYLE in
	Ubuntu)
		apt-get install --yes ubiquity ubiquity-frontend-gtk ubiquity-slideshow-ubuntu
		;;
	Kubuntu)
		apt-get install --yes ubiquity ubiquity-frontend-kde ubiquity-slideshow-kubuntu
		;;
	Xubuntu)
		apt-get install --yes ubiquity ubiquity-frontend-gtk ubiquity-slideshow-xubuntu
		;;
	Lubuntu)
		apt-get install --yes ubiquity ubiquity-frontend-gtk ubiquity-slideshow-lubuntu
		;;
esac
EOF
######################### on EXIT #########################
echo "apt-get clean
rm -rf /tmp/*
rm -rf /etc/hosts
umount -lf /proc
umount -lf /sys
umount -lf /dev/pts
umount -lf /var/lib/dbus
umount -lf /var/run/dbus" >> $FSPATH/tmp/script.bash

sudo chroot $FSPATH sh /tmp/script.bash
umount -l $FSPATH/dev)|
zenity --progress --pulsate --auto-kill --auto-close

###################### Setting up ######################

# FrontEnd
if [ -d $FSPATH/usr/share/ubiquity/gtk ]; then
	echo "ubiquity-frontend-gtk" > $WORKPATH/configs/ubiquity/FRONTEND
elif [ -d $FSPATH/usr/share/ubiquity/qt ]; then
	echo "ubiquity-frontend-kde" > $WORKPATH/configs/ubiquity/FRONTEND
fi

# SlideShow
if [ -e $FSPATH/usr/share/ubiquity-slideshow/slides/icons/gtg.png ]; then
	echo "ubiquity-slideshow-ubuntu" > $WORKPATH/configs/ubiquity/SLIDESHOW
elif [ -e $FSPATH/usr/share/ubiquity-slideshow/slides/icons/kubuntu-logo.png ]; then
	echo "ubiquity-slideshow-kubuntu" > $WORKPATH/configs/ubiquity/SLIDESHOW
elif [ -e $FSPATH/usr/share/ubiquity-slideshow/slides/images/xfce-logo.png ]; then
	echo "ubiquity-slideshow-xubuntu" > $WORKPATH/configs/ubiquity/SLIDESHOW
elif [ -e $FSPATH/usr/share/ubiquity-slideshow/slides/images/lubuntu-logo.png ]; then
	echo "ubiquity-slideshow-lubuntu" > $WORKPATH/configs/ubiquity/SLIDESHOW
fi
}

function ubiquity_remove()
{
(echo
echo STARTING UBIQUITY REMOVE
echo

cp /etc/hosts $FSPATH/etc/

mount --bind /dev $FSPATH/dev
mount --bind /var/run/dbus $FSPATH/var/lib/dbus
mount --bind /var/run/dbus $FSPATH/var/run/dbus

echo "# Removing all Ubiquity files and folders"

touch $FSPATH/tmp/script.bash
cat > $FSPATH/tmp/script.bash << "EOF"
#################### CHROOT ENVIRONMENT ####################
#!/bin/bash

export HOME=/root
export LC_ALL=C
mount none -t proc /proc
mount none -t sysfs /sys
mount none -t devpts /dev/pts

apt-get purge -y ubiquity*

EOF
######################### on EXIT #########################
echo "apt-get clean
rm -rf /tmp/*
rm -rf /etc/hosts
umount -lf /proc
umount -lf /sys
umount -lf /dev/pts
umount -lf /var/lib/dbus
umount -lf /var/run/dbus" >> $FSPATH/tmp/script.bash

sudo chroot $FSPATH sh /tmp/script.bash
umount -l $FSPATH/dev)|
zenity --progress --pulsate --auto-kill --auto-close
}

case "$1" in
	--install)
		ubiquity_install
		;;
	--change)
		ubiquity_change
		;;
	--remove)
		ubiquity_remove
		;;
esac
